# Automatic merging of approved PRs
#
# This file can be edited and validated using:
# https://dashboard.mergify.com/github/trusted-isogenies

queue_rules:
  - name: primary
    allow_inplace_checks: True
    allow_checks_interruption: True
    speculative_checks: 1
    # batching disabled for free open source plans
    # batch_size: 20
    # Wait for about 10% of the time it takes Rust PRs to run CI (3h)
    batch_max_wait_time: "20 minutes"
    conditions:
      - base=main

pull_request_rules:
  - name: move to primary queue when CI passes with 1 review and not WIP targeting main
    conditions:
      # This queue handles a PR if:
      # - it targets main
      # - is not in draft
      # - does not include the do-not-merge label
      # - is labeled with any other priority except Critical, or does not have a priority label,
      #   including automated dependabot PRs.
      #
      # We don't need to check priority labels here, because the rules are evaluated in order:
      # https://docs.mergify.com/configuration/#pull-request-rules
      - base=main
      - -draft
      - label!=do-not-merge
    actions:
      queue:
        name: primary
        method: squash
