# Automatic merging of approved PRs
#
# This file can be edited and validated using:
# https://dashboard.mergify.com/github/trusted-isogenies

queue_rules:
  - name: primary
    queue_conditions:
      - base=main
      - -draft
      - label!=do-not-merge
    merge_conditions:
      - base=main
    allow_inplace_checks: true
    batch_max_wait_time: "20 minutes"
    merge_method: squash

pull_request_rules:
  - name: move to primary queue when CI passes with 1 review and not WIP targeting
      main
    conditions: []
    actions:
      queue:

priority_rules:
  - name: Priority rule from queue `primary`
    conditions:
      - base=main
      - -draft
      - label!=do-not-merge
    allow_checks_interruption: true

merge_queue:
  max_parallel_checks: 1
