[package]
name = "trusted-curve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
thiserror = "1.0.37"

[build-dependencies]
bindgen = "0.61.0"
octocrab = "0.17.0"
